name: testing
on:
  push:
    branches:
      - master
  
      
jobs: 
  deployment:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    env:
      CI: false
    
   


    steps:
    - name: Manual Workflow Approval
      uses: trstringer/manual-approval@v1.8.0
      secret: ${{ secrets.GITHUB_TOKEN  }}
      approvers: consoleLogIt
      minimum-approvals: 1
      issue-title: "Deploying to prod from staging"
      exclude-workflow-initiator-as-approver: false

    - name: Checkout
      uses: actions/checkout@v3

  