name: deploy to prod

on:
  workflow_dispatch:
  
  
      
jobs: 
  deployment:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    env:
      CI: false
    
    permissions: 
      contents: write
      id-token: write


    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name : commands
      run : node -v

  
