name: testing
on:
  workflow_dispatch:
   push:
    branches:
      - 'master'
  
      
jobs: 
  deployment:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    env:
      CI: false
    
    permissions: 
      contents: write
      id-token: write


    steps:
    - name: Checkout
      uses: actions/checkout@v3

  